import { SITE_URL } from "@/lib/seo-config";

/**
 * Dynamic robots.txt generated by Next.js App Router.
 * Automatically served at /robots.txt
 */
export default function robots() {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/api/", "/_next/"],
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
